repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # must match requirements_dev.txt
    hooks:
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-case-conflict
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.5 # must match requirements_dev.txt
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
        types: [file]
        types_or: [python, pyi]
  - repo: https://github.com/psf/black
    rev: 23.7.0 # must match requirements_dev.txt
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # must match requirements_dev.txt
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # must match requirements_dev.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear==23.3.23" # must match requirements_dev.txt
          - "flake8-noqa==1.3.1" # must match requirements_dev.txt
        types: [file]
        types_or: [python, pyi]

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [flake8]
  submodules: false
